import type { DemoTrack } from '@/features/groovy-player/demo-tracks'

import type { Snippet, SnippetInstrument } from '@/features/garage/snippet.types'

const parseTrackBars = (notation: string) =>
  notation
    .split('|')
    .map((bar) => bar.trim())
    .filter((bar) => bar.length > 0)

const track = (id: string, name: string, instrument: string, notation: string): DemoTrack => ({
  id,
  name,
  instrument,
  bars: parseTrackBars(notation),
})

const djembeSet = (prefix: string, notation: string) => [
  track(`${prefix}-djembe`, 'Djembe', 'djembe', notation),
  track(`${prefix}-dundunba`, 'Dundunba', 'dundunba', 'o-o---|--oo-o'),
  track(`${prefix}-sangban`, 'Sangban', 'sangban', 'o---x-|x--o--'),
  track(`${prefix}-kenkeni`, 'Kenkeni', 'kenkeni', '----oo'),
]

const longestTrackBars = (tracks: DemoTrack[]) => Math.max(...tracks.map((t) => t.bars.length))

const snippet = (
  id: string,
  name: string,
  meter: 3 | 4,
  instruments: SnippetInstrument[],
  artist: string[],
  origin: string[],
  tags: string[],
  addedAt: string,
  tracks: DemoTrack[],
): Snippet => ({
  id,
  name,
  meter,
  instruments,
  longestTrack: longestTrackBars(tracks),
  artist,
  origin,
  tags,
  addedAt,
  tracks,
})

export const MOCK_SNIPPETS: Snippet[] = [
  snippet(
    'djaa',
    'Djaa',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta', 'Fadouba Oularé'],
    ['Kouroussa', 'Hamana'],
    ['traditional', 'groove', 'call & response'],
    '2026-06-14T10:00:00Z',
    djembeSet('djaa', 'ttsb-s|b-sb-s|ttsb-s|b-sb-s|[ss]ssstt|-ssstt|ts---[tt]|[tt]tbsb-'),
  ),
  snippet(
    'soli',
    'Soli',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni', 'bell'],
    ['Famoudou Konaté', 'Mamady Keïta'],
    ['Hamana', 'Guinea'],
    ['traditional', 'initiation', 'polyrhythmic', 'unisono'],
    '2026-06-13T09:30:00Z',
    djembeSet('soli', 'ss{ttsstt}|sstss-|f-sf-s|f-fss-|sss-ss|s-sss-|f-tt-t|t-tt--'),
  ),
  snippet(
    'gine-fare',
    'Gine Fare',
    4,
    ['djembe', 'dundunba', 'sangban'],
    ['Mamady Keïta'],
    ['Susu', 'Boke'],
    ['traditional', 'susu', 'groove'],
    '2026-06-12T14:20:00Z',
    djembeSet('gine-fare', 'b---[ss]s|sst--t|tsttst|t-ssbb|b---[ss]s|sst--t|tsttst|ts-b-b'),
  ),
  snippet(
    'kuku',
    'Kuku',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta', 'Bolokada Conde'],
    ['Hamana', 'Farabanah'],
    ['traditional', 'celebration', 'groove'],
    '2026-06-11T11:00:00Z',
    djembeSet('kuku', 'tt--tt|b--b--|tt--tt|b--b--|ssssss|bbbbbb'),
  ),
  snippet(
    'sinte',
    'Sinte',
    4,
    ['djembe', 'dundunba', 'sangban'],
    ['Famoudou Konaté'],
    ['Casamance', 'Senegal'],
    ['traditional', 'sabar-influenced', 'break'],
    '2026-06-10T16:45:00Z',
    djembeSet('sinte', 't-s-t-|b---b|t-s-t-|b---b|sssttt|bbb---'),
  ),
  snippet(
    'lamban',
    'Lamban',
    4,
    ['djembe', 'dundunba', 'kenkeni', 'bell'],
    ['Mamady Keïta', 'Adama Dramé'],
    ['Mali', 'Bamako'],
    ['traditional', 'griot', 'storytelling', 'intro'],
    '2026-06-09T08:15:00Z',
    djembeSet('lamban', 't---t-|s---s|t---t-|s---s|b---b-|o---o'),
  ),
  snippet(
    'sunu',
    'Sunu',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta'],
    ['Bamako', 'Mali'],
    ['traditional', 'wedding', 'kassonke', 'groove'],
    '2026-06-08T13:30:00Z',
    djembeSet('sunu', 'ss-b-ss|bb-b-bb|ss-b-ss|bb-b-bb|tttttt|bbbbbb'),
  ),
  snippet(
    'sofa',
    'Sofa',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Famoudou Konaté', 'Mamady Keïta'],
    ['Kurussa', 'Upper Guinea'],
    ['traditional', 'hunter', 'call & response'],
    '2026-06-07T10:50:00Z',
    djembeSet('sofa', 'b-s-b-s|t-t-t-t|b-s-b-s|t-t-t-t|ssssss|oooooo'),
  ),
  snippet(
    'mendiani',
    'Mendiani',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni', 'bell'],
    ['Mamady Keïta', 'Nansady Keïta'],
    ['Kouroussa', 'Maninka'],
    ['traditional', 'women', 'ballet', 'unisono'],
    '2026-06-06T17:00:00Z',
    djembeSet('mendiani', 's-s-s-s|b-b-b-b|t-t-t-t|s-s-s-s|bbbbbb|tttttt'),
  ),
  snippet(
    'djole',
    'Djole',
    4,
    ['djembe', 'dundunba', 'sangban'],
    ['Famoudou Konaté', 'Fodé Lassana Diabaté'],
    ['Guinea Coast', 'Boke'],
    ['traditional', 'mask', 'celebration', 'polyrhythmic'],
    '2026-06-05T12:10:00Z',
    djembeSet('djole', 'ss-ss-|bb-bb-|ss-ss-|bb-bb-|tttttt|bbbbbb'),
  ),
  snippet(
    'tiriba',
    'Tiriba',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta'],
    ['Faranah', 'Guinea'],
    ['traditional', 'modern', 'groove', 'break'],
    '2026-06-04T09:40:00Z',
    djembeSet('tiriba', 'tbs-tbs|tbs-tbs|ssssss|bbbbbb|tttttt|bbbbbb'),
  ),
  snippet(
    'afri',
    'Afri',
    4,
    ['djembe', 'dundunba', 'sangban'],
    ['Mamady Keïta'],
    ['Susu', 'Boke'],
    ['traditional', 'susu', 'intro', 'outro'],
    '2026-06-03T15:25:00Z',
    djembeSet('afri', 'b---b-|s---s|b---b-|s---s|tttttt|bbbbbb'),
  ),
  snippet(
    'yamama',
    'Yamama',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Bolokada Conde'],
    ['Hamana', 'Guinea'],
    ['traditional', 'bird', 'call & response'],
    '2026-06-02T11:55:00Z',
    djembeSet('yamama', 't-t---|b-b---|t-t---|b-b---|ssssss|bbbbbb'),
  ),
  snippet(
    'sorsonet',
    'Sorsonet',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni', 'bell'],
    ['Famoudou Konaté'],
    ['Boke', 'Guinea'],
    ['traditional', 'mask', 'polyrhythmic'],
    '2026-06-01T08:00:00Z',
    djembeSet('sorsonet', 'ss-bb-|tt-bb-|ss-bb-|tt-bb-|bbbbbb|tttttt'),
  ),
  snippet(
    'kassa',
    'Kassa',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta', 'Adama Dramé'],
    ['Mali', 'Bamako'],
    ['traditional', 'harvest', 'work', 'groove'],
    '2026-05-31T14:30:00Z',
    djembeSet('kassa', 'b-b-b-b|t-t-t-t|b-b-b-b|t-t-t-t|ssssss|bbbbbb'),
  ),
  snippet(
    'soli-rapide',
    'Soli Rapide',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta'],
    ['Hamana', 'Guinea'],
    ['modern', 'ballet', 'break', 'unisono'],
    '2026-05-30T10:20:00Z',
    djembeSet('soli-rapide', 'ssssss|bbbbbb|tttttt|bbbbbb|ssssss|bbbbbb'),
  ),
  snippet(
    'toro',
    'Toro',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Famoudou Konaté'],
    ['Kurussa', 'Guinea'],
    ['traditional', 'elephant', 'call & response'],
    '2026-05-29T16:00:00Z',
    djembeSet('toro', 'b---s-|t---b-|b---s-|t---b-|ssssss|bbbbbb'),
  ),
  snippet(
    'kakilambe',
    'Kakilambe',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni', 'bell'],
    ['Mamady Keïta', 'Fodé Lassana Diabaté'],
    ['Baga', 'Guinea Coast'],
    ['traditional', 'mask', 'spirit', 'polyrhythmic'],
    '2026-05-28T09:10:00Z',
    djembeSet('kakilambe', 'b-b---|s-s---|b-b---|s-s---|tttttt|bbbbbb'),
  ),
  snippet(
    'soko',
    'Soko',
    4,
    ['djembe', 'dundunba', 'sangban'],
    ['Bolokada Conde'],
    ['Hamana', 'Farabanah'],
    ['traditional', 'initiation', 'groove'],
    '2026-05-27T13:45:00Z',
    djembeSet('soko', 'tt-bb-|ss-bb-|tt-bb-|ss-bb-|bbbbbb|tttttt'),
  ),
  snippet(
    'wassolon',
    'Wassolon',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta'],
    ['Wassolon', 'Guinea'],
    ['traditional', 'kassonke', 'unisono'],
    '2026-05-26T11:30:00Z',
    djembeSet('wassolon', 's-s-b-b|t-t-b-b|s-s-b-b|t-t-b-b|ssssss|bbbbbb'),
  ),
  snippet(
    'sangban-break',
    'Sangban Break',
    3,
    ['sangban', 'kenkeni', 'bell'],
    ['Famoudou Konaté'],
    ['Hamana', 'Guinea'],
    ['modern', 'break', 'dundun', 'intro'],
    '2026-05-25T08:50:00Z',
    [
      track('sangban-break-sangban', 'Sangban', 'sangban', 'o---x-|x--o--|o---x-'),
      track('sangban-break-kenkeni', 'Kenkeni', 'kenkeni', '----oo|----oo'),
      track('sangban-break-bell', 'Bell', 'bell', 'x---x-|x---x-'),
    ],
  ),
  snippet(
    'dundungbe',
    'Dundungbe',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Famoudou Konaté', 'Mamady Keïta'],
    ['Hamana', 'Guinea'],
    ['traditional', 'power', 'groove', 'unisono'],
    '2026-05-24T15:15:00Z',
    djembeSet('dundungbe', 'bbbbbb|tttttt|bbbbbb|tttttt|ssssss|bbbbbb'),
  ),
  snippet(
    'moribayassa',
    'Moribayassa',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Mamady Keïta'],
    ['Kouroussa', 'Guinea'],
    ['traditional', 'celebration', 'oath', 'call & response'],
    '2026-05-23T10:05:00Z',
    djembeSet('moribayassa', 'ss-b-ss|bb-b-bb|ss-b-ss|bb-b-bb|tttttt|bbbbbb'),
  ),
  snippet(
    'koreduga',
    'Koreduga',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni'],
    ['Adama Dramé'],
    ['Mali', 'Bamako'],
    ['traditional', 'kassonke', 'groove'],
    '2026-05-22T12:40:00Z',
    djembeSet('koreduga', 't-s-b-|t-s-b-|b-s-t-|b-s-t-|ssssss|bbbbbb'),
  ),
  snippet(
    'sinte-modern',
    'Sinte (Modern)',
    4,
    ['djembe', 'dundunba', 'sangban', 'kenkeni', 'bell'],
    ['Fodé Lassana Diabaté'],
    ['Conakry', 'Guinea'],
    ['modern', 'ballet', 'break', 'groove'],
    '2026-05-21T09:00:00Z',
    djembeSet('sinte-modern', 'sssttt|bbb---|sssttt|bbb---|tttttt|bbbbbb'),
  ),
]

export const filterOptionsFromSnippets = (snippets: Snippet[]) => ({
  meter: [3, 4] as const,
  instruments: ['djembe', 'dundunba', 'sangban', 'kenkeni', 'bell'] as const,
  artist: [...new Set(snippets.flatMap((s) => s.artist))].sort(),
  origin: [...new Set(snippets.flatMap((s) => s.origin))].sort(),
  tags: [...new Set(snippets.flatMap((s) => s.tags))].sort(),
})

export const GARAGE_FILTER_OPTIONS = filterOptionsFromSnippets(MOCK_SNIPPETS)
